apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: CLUSTER_NAME
  region: AWS_REGION

nodeGroups:
  - name: ng-1-workers
    instanceType: EKS_NODE_SIZE
    desiredCapacity: NUMBER_OF_NODES
